version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=rdelacruz
      - POSTGRES_PASSWORD=wMt4NoTZcEdoy63xhJ69
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  postgres-e2e:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store_e2e
      - POSTGRES_USER=rdelacruz_e2e
      - POSTGRES_PASSWORD=wMt4NoTZcEdoy63xhJ69
    ports:
      - 5433:5432
